language: node_js
node_js: 10
install:
- npm install
- cd ./client && npm install
script: yarn test
deploy:
  provider: heroku
  app: read-it-later-testing
  run:
    - "npm install"
    - "cd ./client && npm install"
    - "npm run build"
    - "echo 123"
    - "cd ../server && npm run start-server"
  api_key:
    secure: M84qcxZ3cgLCTd0tCq7Yhnnt8S1hDMiv9gLU0SXJUU7qcK704NBiSam0Xv/CrI325l0zkUmfc+cja7S8UPsq+aBT5781NZeVwC/NXRCVO+ts9iZaLl1JTClbyc1RlAp1nBwaIMIa/QX0z40W+hz5JSdJXYTh3szypKb+2ym8N3bKrqBRzYDT2/AZ7+PHQ9KgZzRobvICyF5qyOCJU8AKvAziBwik6tOETxohDoyFFbkn3T+JiXf5eF8cWO678MU57Gfr77Hhpx8+zqSGuax0q5P+OrA1gfBhTjNEkBxGO53iPx40N5oNiqF6oTJmZp8MuTOp8TBW2bk5ivi/jFKGEdOHQJ2pH3vwPeQfCIeXDG+z2xwJMEQuJuKDgojrf6OreWuqs0zZVkHP2D+fHj896DhsT5f6XNE6p4Zl7/1BWPvbyvLPR0HLWvpIH6yzFZiAfn3fcmG5ic0LRiz+mWeRNnLqeH/VuUPtJCDNrxztZHCmZmQ8xQhaPuSy0uI76g0WEyKRP6wYo8lZkrbtzfo0WZbvUHPP5FBGhTUb2sqrhCx0nNinrsQGQNc2qP+dsV3/wrE41z+vkjsRhfoRlyPhEwYuCrEFjSaU//HYNoFb998Lhd5lSuo0QEmsc7MRIOjz5CcpstJ84/AiG+P8ZV+JIjVZMI7SOL2TUG5C0Yyw/BQ=
